### ISSUE TITLE
Messages and Notifications Sections

### ISSUE THREAD

**Issue by bluishfluid666** [wonrax/bkstinfo#1]
Please add View Messages and Notifications features to the app. This certainly will help a lot.

**Comment by wonrax** [comment]
These features are related to the current e-learning system which are fully supported on the Moodle mobile app so I don't see no point in adding them to this app.

**Comment by bluishfluid666** [comment]
I see a lot of potential in your app, which currently only represents MyBk. The thing is, the current Moodle-based app feels like an incohesive patchwork, giving out a really underwhelming experience, while Hanoi HUST has its own app representing the whole school ecosystem, which is really polished and helps students feel comfortable managing their courses and student info. I don't see why our school cannot do the same.

**Comment by wonrax** [comment]
Well, the thing is, what this app is doing is basically reverse engineering. Our school doesn't provide any kind of official API to access student data, and I had to inspect every single network request just to make this app work. When the school will change the API in some ways, it'll break the app and you have to push a fix every time they do so.

Implementing the e-learning system into the app increases the risk many times more since you have more things to take care of. I believe the mobile team at HUST had the support and authority of their school officials (e.g. API, resource), so they were able to build a more feature-rich, stable, and error-prone app.

Our school had also made a promise that they release an official app, and they are currently forbidding any development of unofficial ones. That's why this app is just a bandaid and I haven't been able to promote it to a wider audience.

Moreover, I'm graduating this semester, so I might not be able to access the system in the near future. If there's anyone interested, I can make them a repo maintainer. I can still help with the product design and tech.
